# Generated by Django 5.0 on 2023-12-15 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billSundryName', models.CharField(max_length=255)),
                ('Amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('InvoiceNumber', models.IntegerField(unique=True)),
                ('CustomerName', models.CharField(max_length=255)),
                ('BillingAddress', models.TextField()),
                ('GSTIN', models.TextField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('invoice_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_App.header')),
            ],
        ),
    ]
