# Generated by Django 5.0 on 2023-12-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillSundry',
        ),
    ]
